In [188]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
 
print(tf.__version__)
print(tf.keras.__version__)

2.0.0
2.2.4-tf


In [198]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(32,activation='relu'),
  
  tf.keras.layers.Dropout(rate=0.1),
  tf.keras.layers.BatchNormalization(),
    
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dense(64, activation='relu'),
 
  tf.keras.layers.Dense(10, activation='softmax')
])
# 载入数据
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = x_train.reshape(60000, 784).astype('float32') /255
x_test = x_test.reshape(10000, 784).astype('float32') /255

x_val = x_train[-10000:]
y_val = y_train[-10000:]

x_train = x_train[:-10000]
y_train = y_train[:-10000]


model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


# 训练模型
history = model.fit(x_train, y_train, batch_size=64, epochs=3,
         validation_data=(x_val, y_val))
print('history:')
print(history.history)


result = model.evaluate(x_test, y_test, batch_size=128)
print('evaluate:')
print(result)
pred = model.predict(x_test[:2])
print('predict:')
print(pred)


Train on 50000 samples, validate on 10000 samples
Epoch 1/3
50000/50000 [==============================] - 3s 57us/sample - loss: 0.4456 - accuracy: 0.8651 - val_loss: 0.1891 - val_accuracy: 0.9423
Epoch 2/3
50000/50000 [==============================] - 2s 43us/sample - loss: 0.2259 - accuracy: 0.9312 - val_loss: 0.1443 - val_accuracy: 0.9565
Epoch 3/3
50000/50000 [==============================] - 2s 43us/sample - loss: 0.1915 - accuracy: 0.9413 - val_loss: 0.1371 - val_accuracy: 0.9599
history:
{'loss': [0.4456395349645615, 0.22590792300224305, 0.19146517577409744], 'val_accuracy': [0.9423, 0.9565, 0.9599], 'accuracy': [0.86506, 0.93124, 0.94134], 'val_loss': [0.1890657295361161, 0.14432051001340152, 0.13705922202914952]}
10000/1 [================================================================================================================================================================================================================================================================

evaluate:
[0.1361962914288044, 0.958]
predict:
[[1.2834513e-06 2.5036650e-07 3.2555984e-04 4.6618534e-05 1.0668746e-08
  4.7990984e-06 3.1432084e-09 9.9960166e-01 1.1519391e-05 8.3724271e-06]
 [3.9223763e-05 3.7613285e-05 9.9931550e-01 5.8456836e-04 9.4194360e-07
  6.5714662e-06 4.2748748e-06 5.1770922e-07 1.0795601e-05 8.9606740e-09]]


In [190]:
###function API构建模型###
# 模型构造
inputs = keras.Input(shape=(784,), name='mnist_input')

h1=layers.Dropout(rate=0.1)(inputs)
h1=layers.BatchNormalization()(h1)

h1 = layers.Dense(64, activation='relu')(h1)
h1 = layers.Dense(64, activation='relu')(h1)
outputs = layers.Dense(10, activation='softmax')(h1)
model = keras.Model(inputs, outputs)
# keras.utils.plot_model(model, 'net001.png', show_shapes=True)

model.compile(optimizer=keras.optimizers.RMSprop(),
             loss=keras.losses.SparseCategoricalCrossentropy(),
             metrics=[keras.metrics.SparseCategoricalAccuracy()])

# 载入数据
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = x_train.reshape(60000, 784).astype('float32') /255
x_test = x_test.reshape(10000, 784).astype('float32') /255

x_val = x_train[-10000:]
y_val = y_train[-10000:]

x_train = x_train[:-10000]
y_train = y_train[:-10000]



In [191]:
tf.keras.backend.set_learning_phase(True)
# 训练模型
history = model.fit(x_train, y_train, batch_size=64, epochs=3,
         validation_data=(x_val, y_val))
print('history:')
print(history.history)



Train on 50000 samples, validate on 10000 samples
Epoch 1/3
50000/50000 [==============================] - 3s 64us/sample - loss: 0.3144 - sparse_categorical_accuracy: 0.9036 - val_loss: 0.1514 - val_sparse_categorical_accuracy: 0.9541
Epoch 2/3
50000/50000 [==============================] - 3s 53us/sample - loss: 0.1544 - sparse_categorical_accuracy: 0.9520 - val_loss: 0.1299 - val_sparse_categorical_accuracy: 0.9615
Epoch 3/3
50000/50000 [==============================] - 3s 53us/sample - loss: 0.1204 - sparse_categorical_accuracy: 0.9629 - val_loss: 0.1092 - val_sparse_categorical_accuracy: 0.9701
history:
{'loss': [0.3144390805912018, 0.15435883901715278, 0.12043334562659264], 'sparse_categorical_accuracy': [0.90364, 0.952, 0.96294], 'val_loss': [0.15138822506070138, 0.12987320883721112, 0.10917656694725156], 'val_sparse_categorical_accuracy': [0.9541, 0.9615, 0.9701]}


In [194]:
tf.keras.backend.set_learning_phase(False)
result = model.evaluate(x_test, y_test, batch_size=128)
print('evaluate:')
print(result)
pred = model.predict(x_test[:2])
print('predict:')
print(pred)


10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

evaluate:
[0.11430991161549464, 0.9685]
predict:
[[1.2269540e-07 4.1142004e-10 7.7295505e-07 2.0889553e-05 1.1102247e-08
  3.3998560e-07 1.2786042e-12 9.9997509e-01 3.4467624e-09 2.7664857e-06]
 [1.8993388e-08 1.0413202e-07 9.9999988e-01 1.7837422e-09 2.4758167e-15
  7.0755590e-10 6.4188577e-10 1.1140538e-15 1.1316393e-10 2.7734827e-14]]


In [160]:
class MyModel(tf.keras.Model):
    def __init__(self, num_classes=10,rate=0.1):
        super(MyModel, self).__init__(name='my_model')
        self.num_classes = num_classes
        
        self.layer1 = layers.Dense(32, activation='relu')
        
        self.dropout1 = layers.Dropout(rate)
        self.batch_norm1=layers.BatchNormalization()
       
        
        self.layer2 = layers.Dense(num_classes, activation=None)
    def call(self, inputs,training=None):
        inputs=self.dropout1 (inputs,training=training)
        inputs = self.batch_norm1(inputs,training=training)
        h1 = self.layer1(inputs)
        out = self.layer2(h1)
        return out
    
    def compute_output_shape(self, input_shape):
        shape = tf.TensorShapej(input_shape).as_list()
        shape[-1] = self.num_classes
        return tf.TensorShape(shape)


In [182]:
# 载入数据
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train.reshape(60000, 784).astype('float32') /255
x_test = x_test.reshape(10000, 784).astype('float32') /255

x_val = x_train[-10000:]
y_val = y_train[-10000:]

x_train = x_train[:-10000]
y_train = y_train[:-10000]

In [183]:
x_train.shape

(50000, 784)

In [184]:
y_train.shape

(50000,)

In [185]:
# import numpy as np

# x_train = np.random.random((1000, 72))
# y_train= np.random.random((1000, 10))

# x_val = np.random.random((200, 72))
# y_val= np.random.random((200, 10))


In [186]:
model = MyModel(num_classes=10)
model2 = MyModel2(num_classes=10)


TypeError: super(type, obj): obj must be an instance or subtype of type

In [166]:
#为训练选择优化器与损失函数：
# Instantiate an optimizer to train the model.
# optimizer=tf.keras.optimizers.RMSprop(0.001)
# optimizer = tf.keras.optimizers.Adam()
             
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-3)
# Instantiate a loss function.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
# loss_fn=tf.keras.losses.categorical_crossentropy()

In [167]:
#选择衡量指标来度量模型的损失值（loss）和准确率（accuracy）。这些指标在 epoch 上累积值，然后打印出整体结果
train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

test_loss = tf.keras.metrics.Mean(name='test_loss')
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')



In [168]:
train_step_signature = [
    tf.TensorSpec(shape=(None,784), dtype=tf.float32),
    tf.TensorSpec(shape=(None,), dtype=tf.uint8),
]

In [169]:
#使用 tf.GradientTape 来训练模型：

##input_signature限定输入的shape和dtype
@tf.function(input_signature=train_step_signature)
# @tf.function()
def train_step(x_batch_train, y_batch_train):
    with tf.GradientTape() as tape:
              predictions = model(x_batch_train,training=True)
              loss_value = loss_fn(y_batch_train, predictions)
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
      
    
    train_loss(loss_value)
    train_accuracy(y_batch_train, predictions)





In [170]:
#测试模型：
@tf.function(input_signature=train_step_signature)
# @tf.function()
def test_step(x_batch_train, y_batch_train):
          predictions = model(x_batch_train,training=False)
          t_loss = loss_fn(y_batch_train, predictions)

          test_loss(t_loss)
          test_accuracy(y_batch_train, predictions)

In [171]:
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size=32)

# Prepare the validation dataset.
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_dataset = val_dataset.batch(32)


In [159]:
EPOCHS = 30

for epoch in range(EPOCHS):
  # 在下一个epoch开始时，重置评估指标
  train_loss.reset_states()
  train_accuracy.reset_states()
  test_loss.reset_states()
  test_accuracy.reset_states()
  # Iterate over the batches of the dataset.
  for step, (x_batch_train, y_batch_train) in enumerate(train_dataset):
    train_step(x_batch_train, y_batch_train)

  for step, (x_batch_test, y_batch_test) in enumerate(val_dataset):
    test_step(x_batch_test, y_batch_test)

  template = 'Epoch {}, Loss: {}, Accuracy: {}, Test Loss: {}, Test Accuracy: {}'
  print (template.format(epoch+1,
                         train_loss.result(),
                         train_accuracy.result(),
                         test_loss.result(),
                         test_accuracy.result()))

Epoch 1, Loss: 0.4582703113555908, Accuracy: 0.876259982585907, Test Loss: 0.3417046368122101, Test Accuracy: 0.9110999703407288
Epoch 2, Loss: 0.429126113653183, Accuracy: 0.8838599920272827, Test Loss: 0.3192710876464844, Test Accuracy: 0.9164999723434448
Epoch 3, Loss: 0.4031102657318115, Accuracy: 0.8878399729728699, Test Loss: 0.30174073576927185, Test Accuracy: 0.9199000000953674
Epoch 4, Loss: 0.38264182209968567, Accuracy: 0.8921999931335449, Test Loss: 0.287992000579834, Test Accuracy: 0.9228000044822693
Epoch 5, Loss: 0.3651851415634155, Accuracy: 0.8968200087547302, Test Loss: 0.2773740291595459, Test Accuracy: 0.9254999756813049
Epoch 6, Loss: 0.35353174805641174, Accuracy: 0.8995800018310547, Test Loss: 0.2681572735309601, Test Accuracy: 0.9258000254631042
Epoch 7, Loss: 0.34393057227134705, Accuracy: 0.9025200009346008, Test Loss: 0.2593839466571808, Test Accuracy: 0.9280999898910522
Epoch 8, Loss: 0.3295055031776428, Accuracy: 0.9038199782371521, Test Loss: 0.25227576494

In [85]:
for step, (x_batch_train, y_batch_train) in enumerate(train_dataset):
    print(x_batch_train)
    print(y_batch_train)
    print(x_batch_train.shape)
    print(y_batch_train.shape)
    break
#     train_step(x_batch_train, y_batch_train)

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(32, 784), dtype=float32)
tf.Tensor([1 2 7 2 4 0 6 0 0 7 0 2 6 4 9 9 0 6 6 9 2 7 6 5 3 3 3 1 3 7 1 5], shape=(32,), dtype=uint8)
(32, 784)
(32,)


In [174]:
tf.keras.backend.set_learning_phase(True)
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-3)
# Instantiate a loss function.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer=optimizer,
             loss=loss_fn,
             metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=16, epochs=5)


Train on 50000 samples
Epoch 1/5
50000/50000 [==============================] - 6s 112us/sample - loss: 1.8678 - accuracy: 0.5643
Epoch 2/5
50000/50000 [==============================] - 5s 102us/sample - loss: 0.7518 - accuracy: 0.7630
Epoch 3/5
50000/50000 [==============================] - 5s 101us/sample - loss: 0.6281 - accuracy: 0.8057
Epoch 4/5
50000/50000 [==============================] - 5s 101us/sample - loss: 0.5566 - accuracy: 0.8275
Epoch 5/5
50000/50000 [==============================] - 5s 101us/sample - loss: 0.5206 - accuracy: 0.8395


In [176]:
tf.keras.backend.set_learning_phase(True)
model.evaluate(x_val,y_val)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.3828072420716286, 0.8872]

In [178]:
model.predict(x_val).shape

(10000, 10)

In [ ]:
tf.keras.backend.set_learning_phase(False)

In [17]:
# 模型构造
inputs = keras.Input(shape=(784,), name='mnist_input')
h1 = layers.Dense(64, activation='relu')(inputs)
h1 = layers.Dense(64, activation='relu')(h1)
outputs = layers.Dense(10, activation='softmax')(h1)
model = keras.Model(inputs, outputs)
# keras.utils.plot_model(model, 'net001.png', show_shapes=True)

model.compile(optimizer=keras.optimizers.RMSprop(),
             loss=keras.losses.SparseCategoricalCrossentropy(),
             metrics=[keras.metrics.SparseCategoricalAccuracy()])

# 载入数据
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = x_train.reshape(60000, 784).astype('float32') /255
x_test = x_test.reshape(10000, 784).astype('float32') /255

x_val = x_train[-10000:]
y_val = y_train[-10000:]

x_train = x_train[:-10000]
y_train = y_train[:-10000]

# 训练模型
history = model.fit(x_train, y_train, batch_size=64, epochs=3,
         validation_data=(x_val, y_val))
print('history:')
print(history.history)

result = model.evaluate(x_test, y_test, batch_size=128)
print('evaluate:')
print(result)
pred = model.predict(x_test[:2])
print('predict:')
print(pred)


11493376/11490434 [==============================] - 1s 0us/step
Train on 50000 samples, validate on 10000 samples
Epoch 1/3
50000/50000 [==============================] - 3s 50us/sample - loss: 0.3430 - sparse_categorical_accuracy: 0.9032 - val_loss: 0.1827 - val_sparse_categorical_accuracy: 0.9469
Epoch 2/3
50000/50000 [==============================] - 2s 40us/sample - loss: 0.1601 - sparse_categorical_accuracy: 0.9520 - val_loss: 0.1251 - val_sparse_categorical_accuracy: 0.9624
Epoch 3/3
50000/50000 [==============================] - 2s 39us/sample - loss: 0.1173 - sparse_categorical_accuracy: 0.9644 - val_loss: 0.1099 - val_sparse_categorical_accuracy: 0.9683
history:
{'sparse_categorical_accuracy': [0.9032, 0.95204, 0.96436], 'val_loss': [0.18268059708476067, 0.1250795459151268, 0.10992885674759746], 'val_sparse_categorical_accuracy': [0.9469, 0.9624, 0.9683], 'loss': [0.3429565958881378, 0.1601492697572708, 0.11731669701516628]}
10000/1 [=========================================

evaluate:
[0.1064200916543603, 0.968]
predict:
[[3.2481788e-07 8.6083276e-08 1.8397326e-04 1.7480092e-04 5.7374505e-10
  4.9884598e-08 8.9255331e-12 9.9963701e-01 4.8994752e-07 3.2399016e-06]
 [3.7270978e-11 1.5680936e-05 9.9998260e-01 1.4245958e-06 5.3867188e-12
  2.7163006e-08 1.4335687e-10 3.2688886e-11 2.5855687e-07 2.6061115e-14]]


In [18]:
# Prepare the training dataset.
batch_size = 64
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)


In [22]:
# Get the model.
inputs = keras.Input(shape=(784,), name='digits')
x = layers.Dense(64, activation='relu', name='dense_1')(inputs)
x = layers.Dense(64, activation='relu', name='dense_2')(x)
outputs = layers.Dense(10, activation='softmax', name='predictions')(x)
model = keras.Model(inputs=inputs, outputs=outputs)

# Instantiate an optimizer.
optimizer = keras.optimizers.SGD(learning_rate=1e-3)
# Instantiate a loss function.
loss_fn = keras.losses.SparseCategoricalCrossentropy()


In [23]:
# 自己构造循环
for epoch in range(3):
    print('epoch: ', epoch)
    for step, (x_batch_train, y_batch_train) in enumerate(train_dataset):
        # 开一个gradient tape, 计算梯度
        with tf.GradientTape() as tape:
            logits = model(x_batch_train)
            
            loss_value = loss_fn(y_batch_train, logits)
            grads = tape.gradient(loss_value, model.trainable_variables)
            optimizer.apply_gradients(zip(grads, model.trainable_variables))
            
        if step % 200 == 0:
            print('Training loss (for one batch) at step %s: %s' % (step, float(loss_value)))
            print('Seen so far: %s samples' % ((step + 1) * 64))


epoch:  0
Training loss (for one batch) at step 0: 2.3346874713897705
Seen so far: 64 samples
Training loss (for one batch) at step 200: 2.196453094482422
Seen so far: 12864 samples
Training loss (for one batch) at step 400: 2.0593466758728027
Seen so far: 25664 samples
Training loss (for one batch) at step 600: 1.9835865497589111
Seen so far: 38464 samples
epoch:  1
Training loss (for one batch) at step 0: 1.9361379146575928
Seen so far: 64 samples
Training loss (for one batch) at step 200: 1.7572753429412842
Seen so far: 12864 samples
Training loss (for one batch) at step 400: 1.7625417709350586
Seen so far: 25664 samples
Training loss (for one batch) at step 600: 1.5512778759002686
Seen so far: 38464 samples
epoch:  2
Training loss (for one batch) at step 0: 1.4622037410736084
Seen so far: 64 samples
Training loss (for one batch) at step 200: 1.3549437522888184
Seen so far: 12864 samples
Training loss (for one batch) at step 400: 1.2561672925949097
Seen so far: 25664 samples
Trainin

In [24]:
# 训练并验证
# Get model
inputs = keras.Input(shape=(784,), name='digits')
x = layers.Dense(64, activation='relu', name='dense_1')(inputs)
x = layers.Dense(64, activation='relu', name='dense_2')(x)
outputs = layers.Dense(10, activation='softmax', name='predictions')(x)
model = keras.Model(inputs=inputs, outputs=outputs)

# Instantiate an optimizer to train the model.
optimizer = keras.optimizers.SGD(learning_rate=1e-3)
# Instantiate a loss function.
loss_fn = keras.losses.SparseCategoricalCrossentropy()

# Prepare the metrics.
train_acc_metric = keras.metrics.SparseCategoricalAccuracy() 
val_acc_metric = keras.metrics.SparseCategoricalAccuracy()

# Prepare the training dataset.
batch_size = 64
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)

# Prepare the validation dataset.
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_dataset = val_dataset.batch(64)


# Iterate over epochs.
for epoch in range(3):
  print('Start of epoch %d' % (epoch,))
  
  # Iterate over the batches of the dataset.
  for step, (x_batch_train, y_batch_train) in enumerate(train_dataset):
    with tf.GradientTape() as tape:
      logits = model(x_batch_train)
      loss_value = loss_fn(y_batch_train, logits)
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
      
    # Update training metric.
    train_acc_metric(y_batch_train, logits)

    # Log every 200 batches.
    if step % 200 == 0:
        print('Training loss (for one batch) at step %s: %s' % (step, float(loss_value)))
        print('Seen so far: %s samples' % ((step + 1) * 64))

  # Display metrics at the end of each epoch.
  train_acc = train_acc_metric.result()
  print('Training acc over epoch: %s' % (float(train_acc),))
  # Reset training metrics at the end of each epoch
  train_acc_metric.reset_states()

  # Run a validation loop at the end of each epoch.
  for x_batch_val, y_batch_val in val_dataset:
    val_logits = model(x_batch_val)
    # Update val metrics
    val_acc_metric(y_batch_val, val_logits)
  val_acc = val_acc_metric.result()
  val_acc_metric.reset_states()
  print('Validation acc: %s' % (float(val_acc),))


Start of epoch 0
Training loss (for one batch) at step 0: 2.3335390090942383
Seen so far: 64 samples
Training loss (for one batch) at step 200: 2.202396869659424
Seen so far: 12864 samples
Training loss (for one batch) at step 400: 2.173975706100464
Seen so far: 25664 samples
Training loss (for one batch) at step 600: 2.11556339263916
Seen so far: 38464 samples
Training acc over epoch: 0.2573600113391876
Validation acc: 0.44769999384880066
Start of epoch 1
Training loss (for one batch) at step 0: 2.0281424522399902
Seen so far: 64 samples
Training loss (for one batch) at step 200: 2.030360698699951
Seen so far: 12864 samples
Training loss (for one batch) at step 400: 1.8267123699188232
Seen so far: 25664 samples
Training loss (for one batch) at step 600: 1.7597312927246094
Seen so far: 38464 samples
Training acc over epoch: 0.5622599720954895
Validation acc: 0.6654999852180481
Start of epoch 2
Training loss (for one batch) at step 0: 1.5773967504501343
Seen so far: 64 samples
Training 