In [24]:
from tensorflow.keras import backend as K
import tensorflow as tf
import numpy as np

w = K.variable(np.random.randint(10,size=(10,12,4,5)))
k = K.variable(np.random.randint(10,size=(10,12,5,8)))
# print(w)
# print(k)
z = K.batch_dot(w,k)
print(z.shape) #(10, 12, 4, 8)



(10, 12, 4, 12, 8)


In [26]:
# help(K.batch_dot)

In [39]:
import tensorflow as tf
import tensorflow.keras.backend as K

x = tf.constant(
[
   [ [1, 2], 
     [3, 4]
   ],
   
    [ [1, 2], 
     [3, 4]
    ]
]
    
)


y = tf.constant(
    [
   [ [2, 3], 
     [4, 5]
   ],
   
    [ [1, 1], 
     [2, 2]
    ]
]
    
)

print(x.shape,y.shape)

# print(K.batch_dot(x, y, axes=1))

# print(K.batch_dot(x, y))
res=K.batch_dot(x, y)
print(res)



(2, 2, 2) (2, 2, 2)
tf.Tensor(
[[[10 13]
  [22 29]]

 [[ 5  5]
  [11 11]]], shape=(2, 2, 2), dtype=int32)


In [43]:


QK = tf.nn.softmax(res)
print(Qk)

RuntimeError: Attempting to capture an EagerTensor without building a function.

In [37]:
x=np.dot( [ [1, 2], 
     [3, 4]
   ], 
    [ [2, 3], 
     [4, 5]
   ],)
print(x)
y=np.dot([ [1, 2], 
     [3, 4]
   ], [ [1, 1], 
     [2, 2]
    ])
print(y)

[[10 13]
 [22 29]]
[[ 5  5]
 [11 11]]


In [7]:
x_batch = K.ones(shape=(2, 2, 1))
y_batch = K.ones(shape=(2, 3, 2))
xy_batch_dot = K.batch_dot(x_batch, y_batch, axes=(1, 2))
print(K.int_shape(xy_batch_dot))
print(xy_batch_dot.shape)


(2, 1, 3)
(2, 1, 3)


In [15]:
x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[5, 6], [7, 8]])
inner_products = []
for xi, yi in zip(x, y):
    print(xi) 
    print(yi)
    print('*')
    inner_products.append(tf.keras.dot(xi,yi))
# result = stack(inner_products)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
*


AttributeError: module 'tensorflow_core.keras' has no attribute 'dot'

In [17]:
from tensorflow.keras import backend as K
a = K.ones((3,4))
b = K.ones((4,5))
c = K.dot(a, b)
print(c.shape)#(3,5)


(3, 5)


In [18]:
a = K.ones((1,2))
b = K.ones((1,2))
c = K.dot(a, b)
print(c.shape)#(3,5)

InvalidArgumentError: Matrix size-incompatible: In[0]: [1,2], In[1]: [1,2] [Op:MatMul] name: MatMul/