In [41]:
import pandas as pd

In [8]:
data=pd.DataFrame([[1,2,3],[4,5,6]],columns=['a','b','c'])

In [9]:
data

a  b  c
0  1  2  3
1  4  5  6

In [26]:
d2=data.stack()
d2

0  a    1
   b    2
   c    3
1  a    4
   b    5
   c    6
dtype: int64

In [13]:
d2.index

MultiIndex(levels=[[0, 1], ['a', 'b', 'c']],
           codes=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [14]:
d2.reset_index()

level_0 level_1  0
0        0       a  1
1        0       b  2
2        0       c  3
3        1       a  4
4        1       b  5
5        1       c  6

In [32]:
d2.unstack(0)

0  1
a  1  4
b  2  5
c  3  6

In [29]:
d2.unstack(1)

a  b  c
0  1  2  3
1  4  5  6

In [30]:
d2.unstack()

a  b  c
0  1  2  3
1  4  5  6

In [23]:
d_series=pd.Series(range(7))
d_series

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64

In [42]:
##numpy stack
# 沿着新轴连接数组序列
import numpy as np

In [48]:
a = [1,2,3,4]
b =[5,6,7,8]

print(np.stack((a,b,b),axis=0))##按照0轴方向,即拼成列

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [47]:
print(np.stack((a,b,a),axis=1))#拼成行

[[1 5 1]
 [2 6 2]
 [3 7 3]
 [4 8 4]]


In [49]:
print(np.hstack((a, b,a)))

print(np.vstack((a,b,a)))

[1 2 3 4 5 6 7 8 1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]
